package review;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import java.util.Calendar;
import java.util.Objects;

/**
 * A deleted review within Amazon Videos.
 */
@DynamoDBTable(tableName = "...")
public class DeletedReview {

    @DynamoDBHashKey
    private String userId;

    @DynamoDBRangeKey
    private String imdbId;

    private Double rating;

    /* The time this review was deleted */
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private Calendar deletedAt;

    /* The time this review was originally created */
    private String createdAt;

    /* The last time this review was updated (before it was deleted) */
    private String updatedAt;

    @DynamoDBVersionAttribute
    private Long version;

    public DeletedReview() {}

    /**
     * Constructs a DeletedReview.
     */
    public DeletedReview(String userId,
                         String imdbId,
                         Double rating,
                         String createdAt,
                         String updatedAt) {
        this.userId = userId;
        this.imdbId = imdbId;
        this.rating = rating;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getImdbId() {
        return imdbId;
    }

    public void setImdbId(String imdbId) {
        this.imdbId = imdbId;
    }

    public Double getRating() {
        return rating;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public Calendar getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(Calendar deletedAt) {
        this.deletedAt = deletedAt;
    }

    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public String getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(String updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public boolean equals(Object other) {
        return other instanceof DeletedReview
                && Objects.equals(userId, ((DeletedReview) other).userId)
                && Objects.equals(imdbId, ((DeletedReview) other).imdbId)
                && Objects.equals(rating, ((DeletedReview) other).rating);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, imdbId, rating);
    }
}
